"""Add sport_id to Event model

Revision ID: 4407908c042b
Revises: 5ae8be932c56
Create Date: 2026-07-11 00:10:06.233365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4407908c042b'
down_revision: Union[str, None] = '5ae8be932c56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('sport_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_events_sport_id'), 'events', ['sport_id'], unique=False)
    op.create_foreign_key(None, 'events', 'sports', ['sport_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_index(op.f('ix_events_sport_id'), table_name='events')
    op.drop_column('events', 'sport_id')
    # ### end Alembic commands ###
